### ISSUE TITLE
Magento 2.2.8 compatibility?

### ISSUE THREAD

**Issue by yacms** [mageplaza/magento-2-smtp#149]
Update my Magento store from 2.2.7 to 2.2.8
Module Version 1.2.9
Core module 1.4.2

Error: Blank page on checkout (Payment success)
Blank page if i try to send an E-Mail via Backend

If i try to send a test E-Mail the loading icon disappears after one second and not error is shown nor an E-Mail is send..

Any known issue with M2 2.2.8?

**Comment by adamrandazzo** [comment]
I can confirm that when placing an order in 2.2.8, I get this error in my ajax console: 

`{"messages":{"error":[{"code":500,"message":"Fatal Error: 'Uncaught Error: Call to undefined method Magento\\Framework\\Mail\\Message::getHeaders() in \/var\/vhosts\/mystore.com\/dev\/vendor\/mageplaza\/module-smtp\/Mail\/Rse\/Mail.php:203\nStack trace:\n#0 \/var\/vhosts\/mystore.com\/dev\/vendor\/mageplaza\/module-smtp\/Mail\/Transport.php(109): Mageplaza\\Smtp\\Mail\\Rse\\Mail->processMessage(Object(Magento\\Framework\\Mail\\Message), '1')\n#1 \/var\/vhosts\/mystore.com\/dev\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Mageplaza\\Smtp\\Mail\\Transport->aroundSendMessage(Object(Magento\\Email\\Model\\Transport\\Interceptor), Object(Closure))\n#2 \/var\/vhosts\/mystore.com\/dev\/vendor\/magento\/module-email\/Model\/Mail\/TransportInterfacePlugin.php(48): Magento\\Email\\Model\\Transport\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#3 \/var\/vhosts\/mystore.com\/dev\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Email\\Model\\Mail\\TransportInterfacePlugin->aroundSendMessage(Object(Magento\\Email\\Model\\Transport\\Intercep' in '\/var\/vhosts\/mystore.com\/dev\/vendor\/mageplaza\/module-smtp\/Mail\/Rse\/Mail.php' on line 203","trace":"Trace is not available."}]}}`

**Comment by adamrandazzo** [comment]
It looks like 2.2.8 version of Magento no longer extends Zend Mail for it's $message class

**Comment by crankycyclops** [comment]
I've just run into this issue as well. Glad to see it's already been reported :)

**Comment by Arthas78** [comment]
Sorry for the late reply. Our working day has started. This problem is due to the Magento 2.2.8 version, they use email flow like Magento 2.3.
Please download and replace the files below, delete the cache and re-test your site. This is the link
https://drive.google.com/file/d/1iG8MTtF45ebubYCooVNmBiQ89jBbqljC/view?usp=sharing
Thank you very much!

**Comment by crankycyclops** [comment]
> Sorry for the late reply. Our working day has started. This problem is due to the Magento 2.2.8 version, they use to send email flow like Magento 2.3.
> Please download and replace the files below, delete the cache and re-test your site. This is the link
> https://drive.google.com/file/d/1iG8MTtF45ebubYCooVNmBiQ89jBbqljC/view?usp=sharing
> Thank you very much!

Hi @Arthas78, thank you! That seems to work on my dev box.

**Comment by yacms** [comment]
Update with your files and cleared the cache. Now i get an Open SSL error: Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /var/www/sites/loewenstein.shop/html/vendor/zendframework/zend-mail/src/Protocol/Smtp.php on line 215

**Comment by mist-01** [comment]
> Sorry for the late reply. Our working day has started. This problem is due to the Magento 2.2.8 version, they use to send email flow like Magento 2.3.
> Please download and replace the files below, delete the cache and re-test your site. This is the link
> https://drive.google.com/file/d/1iG8MTtF45ebubYCooVNmBiQ89jBbqljC/view?usp=sharing
> Thank you very much!

This fixed the issue for me as well on 2.2.8.  Thanks!

**Comment by gclift** [comment]
Mageplaza, thanks for jumping on this issue so quickly. I would just want to help with some testing information. We were also having the same problem. I patched our server with the code above. Emails are now working in the normal customer email flow but when using the "Test Email" in the configuration, we are getting the exception below. We are using TLS over port 587.

[30-Mar-2019 17:27:05 UTC] PHP Fatal error:  Uncaught Exception: Warning: fwrite(): SSL operation failed with code 1. OpenSSL Error messages:
error:140D00CF:SSL routines:SSL_write:protocol is shutdown in .../vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php on line 260 in .../vendor/magento/framework/App/ErrorHandler.php:61

**Comment by Arthas78** [comment]
This is an SSL certificate authentication issue on your server. Please contact the server to help you with this issue

**Comment by archonkulis** [comment]
@Arthas78 

Hey!

I've just upgraded Magento from 2.2.5 to 2.2.8 and now Mageplaza_Smtp gives the following error when creating a customer:

`Fatal error: Uncaught TypeError: Argument 1 passed to Zend_Mail_Transport_Abstract::send() must be an instance of Zend_Mail, instance of Magento\Framework\Mail\Message\Interceptor given, called in app/code/Mageplaza/Smtp/Mail/Transport.php on line 113 and defined in vendor/magento/zendframework1/library/Zend/Mail/Transport/Abstract.php:305`

Full stack trace:

`Stack trace: #0 /var/www/dev/www/app/code/Mageplaza/Smtp/Mail/Transport.php(113): Zend_Mail_Transport_Abstract->send(Object(Magento\Framework\Mail\Message\Interceptor)) #1 /var/www/dev/www/vendor/magento/framework/Interception/Interceptor.php(135): Mageplaza\Smtp\Mail\Transport->aroundSendMessage(Object(Magento\Email\Model\Transport\Interceptor), Object(Closure)) #2 /var/www/dev/www/vendor/dotmailer/dotmailer-magento2-extension/Plugin/TransportPlugin.php(75): Magento\Email\Model\Transport\Interceptor->Magento\Framework\Interception\{closure}() #3 /var/www/dev/www/vendor/magento/framework/Interception/Interceptor.php(135): Dotdigitalgroup\Email\Plugin\Tr in /var/www/dev/www/vendor/magento/zendframework1/library/Zend/Mail/Transport/Abstract.php on line 305`

Can you please check this and let me know how it goes?

Cheers

**Comment by Arthas78** [comment]
I gave the reason and solution for this problem above, look for the solution above(http://prntscr.com/n5qmir)
Thank you very much!

**Comment by yacms** [comment]
> This is an SSL certificate authentication issue on your server. Please contact the server to help you with this issue

The Module worked like a charm before updating to 2.2.8 an now we're facing the SSL Error - nothing changend on our System

`Open SSL error: Warning: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /var/www/sites/customer/html/vendor/zendframework/zend-mail/src/Protocol/Smtp.php on line 215`

**Comment by archonkulis** [comment]
@Arthas78 

Thanks, it fixed the issue. Haven't tried it in the first place as the error in the description was a little different.

Anyway, thanks once again and have a nice day!

**Comment by Arthas78** [comment]
@yacms This is due to your configured server. You can refer the link attached
https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting || http://prntscr.com/n5qx3u

**Comment by OvalMedia** [comment]
Will this be fixed in the repo as well?

**Comment by t-perm** [comment]
Same issue

**Comment by archonkulis** [comment]
@Arthas78 

Just FYI - Magento sent an e-mail recently about security issues and that merchant should upgrade their Magento to at least 2.2.8 version, so I think you will receive a lot of these now if you won't put this into repo :)

**Comment by hypershopbv** [comment]
Any news on when this will be added to the repo?

**Comment by Arthas78** [comment]
We are still checking the compatibility of all modules with new magento versions. We will update as soon as possible

**Comment by AurelienLavorel** [comment]
If you manage installation from composer and got cweagans/composer-patches installed, just add

```
        "patches": {
            "mageplaza/module-smtp": {
                "SMTP working with 2.2.8": "https://patch-diff.githubusercontent.com/raw/AurelienLavorel/magento-2-smtp/pull/1.patch"
            }
        }
```

to the "extra" part of composer.json. 

```
rm -rf -- vendor/mageplaza/module-smtp/
composer install
````

And it should be fine. Don't forget to remove that part after the official release.

**Comment by justinpfister** [comment]
Just confirming the steps @AurelienLavorel provided do work.  I used the `cweagans/composer-patches` (https://support.magento.com/hc/en-us/articles/360005484154-Create-a-patch-for-a-Magento-2-Composer-installation-from-a-GitHub-commit)

And the patch as he noted. Although I didn't use the URL in his example. I put the patch in the patch directory.

```
"patches": {
            "mageplaza/module-smtp": {
                "SMTP working with 2.2.8": "patches/composer/mageplaza_smtp_fix1.patch"
            }
        }
```

**Comment by SnowCommerceBrand** [comment]
For those who are trying to use this patch opened here make sure you are using the most recent version of the module.

**Comment by Arthas78** [comment]
We have released smtp version 1.2.10, you can download it here. Because the new version has been released, I will close this issue. If there are any problems, we will discuss and resolve them in the future. Thank you very much!

**Comment by justinpfister** [comment]
Nice work Arthas78!

**Comment by dharmendrakothe** [comment]
What is solution to resolve this?

**Comment by gclift** [comment]
Upgrade to version 1.2.10 should do the trick.

**Comment by justinpfister** [comment]
Just confirming.. upgrade to 1.2.10 works great.. but understand.. this is
a huge red flag for other modules to break. For example.. all my modules
that sent PDF (ot other attachments) broke when I upgraded to version
2.2.8+. And didn't realize it till it was too late. reverting  back to 2
2.7-  was very difficult.. so please everybody.. test your application
fully before upgrading to 2.2.8+

**Comment by Arthas78** [comment]
@justinpfister Are you using our PDF invoice module? Exactly that module is also having problems sending email attached. we fixed it but are still in the process of finalizing to release a new version. We will try to release a new version of the pdf invoice module as soon as possible

**Comment by Rickertje** [comment]
Can somebody explain why Magento develop makes this kind of changes changes in a security release like 228 ??? Sure they must be aware that there are plenty of modules out there that depend on ZendMail. In my case my custom module attaching pdf broke down. I had major problems fixing it so it could not be installed right away to secure my shop. 
A minor release with security patches like this should not give big headaches !!
And why is attaching a pdf or registering a smtp server still not out-of -the box functionality in the first place. Not even after 10+ years of Magento. These are such basics. 
Boy what a nightmare.

**Comment by 619frank** [comment]
is there any solution for magento 2.2.3 ?

**Comment by kestraly** [comment]
Thank you for the resolution - A minor release shouldn't of had such a major implication

**Comment by selected-pixel-jameson** [comment]
I'm running Magento 2.10.0 and I have version 1.2.10 of this plugin installed. I continue to get this error when ever I try to sign a user up.

I've cleared the Magento cache as well as the Redis Cache. I've tried executing this from HTTPS and from HTTP and I still get the same error. 

`Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Email\Model\Transport::__construct() must be an instance of Magento\Framework\Mail\Message, instance of Zend_Mail_Transport_Sendmail given, called in /app/generated/code/Magento/Email/Model/Transport/Interceptor.php on line 14 and defined in /app/vendor/magento/module-email/Model/Transport.php:72 Stack trace: #0 /app/generated/code/Magento/Email/Model/Transport/Interceptor.php(14): Magento\Email\Model\Transport->__construct(Object(Zend_Mail_Transport_Sendmail), Object(Magento\Framework\Mail\Message\Interceptor), Object(Magento\Framework\App\Config)) #1 /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Magento\Email\Model\Transport\Interceptor->__construct(Object(Zend_Mail_Transport_Sendmail), Object(Magento\Framework\Mail\Message\Interceptor), Object(Magento\Framework\App\Config)) #2 /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Ma in /app/vendor/magento/module-email/Model/Transport.php on line 72`
