### ISSUE TITLE
Magento 2.2.8 Issue

### ISSUE THREAD

**Issue by sashas777** [mageplaza/magento-2-smtp#158]
Hi

When I try to register a customer I getting the following error
 
 `FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Zend_Mail_Transport_Abstract::send() must be an instance of Zend_Mail, instance of Magento\Framework\Mail\Message\Interceptor given, called in /usr/share/nginx/html/vendor/mageplaza/module-smtp/Mail/Transport.php on line 113 and defined in /usr/share/nginx/html/vendor/magento/zendframework1/library/Zend/Mail/Transport/Abstract.php:305
`
 
It seems related that in 2.3.1 updated send function
vendor/magento/framework/Mail/Transport.php
` $this->zendTransport->send(
                ZendMessage::fromString($this->message->getRawMessage())
            );
`

After it replaced in vendor/mageplaza/module-smtp/Mail/Transport.php

There is another issue:
`*1623 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Framework\Mail\Message\Interceptor::getHeaders() in /usr/share/nginx/html/vendor/mageplaza/module-smtp/Model/Log.php:128`

**Comment by Arthas78** [comment]
I tested the SMTP version 1.2.9 on the Magento version 2.3.1 and saw it run normally
It looks like you're using an old version of SMTP, upgrades it to the latest version here
https://github.com/mageplaza/magento-2-smtp

**Comment by sashas777** [comment]
@Arthas78 
Sorry, I was wrong about the version. Magento version 2.2.8

**Comment by Arthas78** [comment]
I had a solution to this problem here
https://github.com/mageplaza/magento-2-smtp/issues/149 || http://prntscr.com/nbojls

**Comment by sashas777** [comment]
@Arthas78  Is it possible to create a patch or update the module? We the module it installed via composer during deployment

**Comment by Arthas78** [comment]
If you have installed this module via composer, find and replace files via the vendor/mageplaza/module-smtp/ path.

**Comment by sashas777** [comment]
@Arthas78 
The way deployment goes - it installs it from the composer each time.
Is there any way to do an update for the module itself?

**Comment by Arthas78** [comment]
You can install smtp 1.2.9 first and add the patch later. or if you can't install it, you can wait for us to release a new version. We are perfecting it and will release soon

**Comment by Arthas78** [comment]
We have released version smtp 1.2.10 you can download it here
https://github.com/mageplaza/magento-2-smtp || http://prntscr.com/ne7ans
Because the new version has been released, I will close this issue

**Comment by jcolas15** [comment]
Hi @Arthas78,

We recently updated to your lastest version 1.2.10 (also this issue is happening on 1.2.9 with the 2.2.8 patches applied) and we tried entering a return path email and are getting the following error.
"Transaction failed: Domain contains illegal character"

It is a normal domain with no special characters.  

Any ideas?

We are on 2.2.8 by the way.

Thanks

**Comment by Arthas78** [comment]
I'm afraid the problem is in your configuration information. Please disable the SMTP module and configure it in dot-mailler of magento. then go out to the frontend to check, if your email is still not sent, I believe your problem does not come from the SMTP module, check with the host or server. You can refer the link
https://groups.google.com/forum/#!topic/openesignformsdev/av9CHYdXaYE
https://developer.salesforce.com/forums/?id=906F00000008ybXIAQ

**Comment by jpelayo** [comment]
I used the development branch with my Magento 2.3.2 php 7.2 . 
This issue seems still happening for Amazon SES email-smtp.eu-west-1.amazonaws.com :

[2019-08-13 13:16:12] main.CRITICAL: Transaction failed: Domain contains illegal character
 {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Transaction failed: Domain contains illegal character
 at /var/www/html/app/code/Mageplaza/Smtp/Mail/Transport.php:132, Zend\\Mail\\Protocol\\Exception\\RuntimeException(code: 0): Transaction failed: Domain contains illegal character
 at /var/www/html/vendor/zendframework/zend-mail/src/Protocol/AbstractProtocol.php:348)"} []

**Comment by gabriel3iri** [comment]
Does anyone knows if this extension is still needed for M 2.2.10? @Arthas7895 ?
