### ISSUE TITLE
Invalid MAIL FROM address provided 

### ISSUE THREAD

**Issue by rramesh2000** [mageplaza/magento-2-smtp#4]
Hi there, 

Getting this error 

Error
Invalid MAIL FROM address provided (Where do u define the from address or which of the store emails does it use when testing)

when i try to test it I am using AWS SES  

Thanks
regards 
Ritesh Ramesh

**Comment by rramesh2000** [comment]
I looked at the code and you are assuming that the username is the from email but AWS SES has a username that is not an email address. 

Might make more sense to use one of the store email addresses for your test. 

cheers 
Ritesh

**Comment by plasmastorm** [comment]
I am also having issues sending via an SMTP account which has a non-email-address formatted username. 

I don't get an error message, but emails arrive from info.storename@mailserver.com rather than info@storename.com like they should. The account's username is info.storename but it is authorised to send as info@storename.com (and sending from this address works fine from the owner's mail client).

**Comment by lmeyer** [comment]
Same problem here with Amazon SES

**Comment by joaoasrosa** [comment]
+1 for Amazon SES.
I nail down to https://github.com/mageplaza/magento-2-smtp/blob/7d619145dbac4ba0ceade556ec5134bbf40eec40/Application/Resource/Mail.php#L112, since it should take into account the e-mail address of the section (Sales, Customer Service, Recover Password).
My PHP skills are low, I can't provide a fix with the quality.

Do you have a workaround (how to hard code a mail), or a proper fix to it?

**Comment by nmallepally** [comment]
Same issue here with send grid sends emails as user name of sendgrid rather than taking the magento 2 sender email address into account.

Any work around for this ?

**Comment by Kroellie** [comment]
+1 Come on guys, it's not that hard to add an "e-mail from"-field... is it?

**Comment by Kroellie** [comment]
By the way, changing $message->setFrom($userName, $senderName); into $message->setFrom("mail@from.com", $senderName); in the aforementioned file is the workaround...

**Comment by quentinfarizon** [comment]
On my side, I removed completely the lines 109 to 113 (https://github.com/mageplaza/magento-2-smtp/blob/01a7148cf768f4ef6aa5a54a111eec7ce2ef3dde/Application/Resource/Mail.php#L109-L113) so that the "From" field uses the sender defined for my store, or the configured general email.
I'm not sure why we want to override the sender (configured in Magento back-office) with the SMTP username (which is a random string on some SMTP providers, Sengrid in my case).

**Comment by inelukipg** [comment]
Same issue for me. Using Mandrill and I don't won't to use the username as sender email address.
It would be great if this could be a setting under configuration.

**Comment by russdeg** [comment]
I have the same issue too. I tried removing the lines as mentioned by @quentinfarizon from Mail.php but it didn't work. I'm using SES.

**Comment by gwharton** [comment]
Yes, there are two areas where the from address are not correctly used.

Application\Resource\Mail.php

Comment out Lines 107-113
`
		//$headers    = $message->getHeaders();
		//$senderName = strip_tags($headers['From'][0], $message->getFrom());
		//$userName   = $this->smtpHelper->getConfig(self::CONFIGURATION_GROUP_SMTP, 'username');
		//if ($userName && $senderName) {
		//	$message->clearFrom();
		//	$message->setFrom($userName, $senderName);
		//}
`
The From address is already set by Magento, as different emails within the store can be set to use different from addresses. Not only is the original code wrong, in that in many cases username is not a valid email address, this module should not be modifying the from address in any way. Thats magento's job.

The second area where the from address is used incorrectly is in the admin page test function.

Controller\Adminhtml\Index\Index.php

Offending Lines 113-115

`			if ($params['username']) {
				$mail->setFrom($config['username']);
			}
`
In this case, as the module is generating the email itself and not Magento, it should look in the Magento settings and retrieve the stores General Contact email address and use that as the from address for the email. It is not valid in this case to use the username field.

**Comment by jspizziri** [comment]
@imsamthomas ,

AWS SES is a massive provider, it'd be great to get this issue addressed.

**Comment by milindkansagara** [comment]
Hello,

I also facing the same issue. We are on AWS and the Email from address is also a verified address but still we are getting following error. When trying to send test email.

2017-12-04 05:36:40] main.CRITICAL: Invalid MAIL FROM address provided
 {"exception":"[object] (Zend_Mail_Protocol_Exception(code: 501): Invalid MAIL FROM address provided
 at /vendor/magento/zendframework1/library/Zend/Mail/Protocol/Abstract.php:431)"} []

Do you have any solution for this?

Thanks & Regards,

**Comment by gwharton** [comment]
4 months later and this is still not fixed, even though two of your customers have generated pull requests that fix it. Please sort it.

**Comment by imsamthomas** [comment]
We fixed this already, please pull latest version

**Comment by gixid192** [comment]
@JoshuaFlood We suggest you removed the old version and use the latest version from the repo.
And here is the fix for Magento 2.2.4 and above: https://github.com/mageplaza/magento-2-smtp/issues/80

**Comment by JoshuaFlood** [comment]
How should I go about installing it?

I just installed the latest version today.

**Comment by gixid192** [comment]
If you are using the latest version then you should check the issue #80

**Comment by JoshuaFlood** [comment]
Just tried that and no luck. Do I need to remove and re-install the smtp plugin once the `sashas/bug-from-email` module is installed? Or should it be working straight away?

**Comment by gixid192** [comment]
Magento 2.2.2 and above shipped with Transaction Email from Dotmailer https://www.screencast.com/t/wSLA3bZsAZkZ

You can use that tool to troubleshoot your store email function. If it doesn't work then your email server and your server have it own issues. You need to fix that issue first.

**Comment by JoshuaFlood** [comment]
The smtp server I use is on port 465, so I can't use dotmailer because it doesn't allow that value.

When I enter incorrect login details and run a test, then I get a response telling me that my login information is incorrect.
When I enter the wrong port I get a 'could not connect to socket' error.

But, when I enter the correct information, the test e-mail is sent successfully and contact e-mail is sent successfully. The frontend displays a message to the user telling them that an e-mail was successfully sent, but I get an invalid sender error when I look at `var/log/system.log`.

If magento is able to perform other e-mail sending functions using the same information and the server is able to successfully send those messages (confirmed recieved in my inbox), then surely the server is handling e-mails perfectly well?

**Comment by JoshuaFlood** [comment]
I mean, magento is sending one email successfully and the other fails, both using the same configuration... meaning that the problem is with magento or this module. Either way, this module is not working.

**Comment by gixid192** [comment]
- Magento is not your Gmail (or whatever mail server you are using with port 465), they are just different.
When you use a Smtp tool, you are using another service which is different from Magento.

- Invalid Sender error, as I told you, is Magento problem which is fixed with #80

You can use PhpMailer to test the sending mail function and also the connection of your mail server https://github.com/PHPMailer/PHPMailer
If it works then the problems come from our extension, we will check it for you.

**Comment by JoshuaFlood** [comment]
Mate I just told you I applied the fix #80 and I still receive the invalid sender error. If it is a magento error then it is obviously magento that has a problem and not my smtp server (already confirmed that my configuration works perfectly well).

You can even see if you follow all the comments for #80, that someone else has commented saying the fix doesn't work for them.

My Web server and the smtp server are functioning perfectly. Magento and your module are not functioning properly. Please help.

**Comment by JoshuaFlood** [comment]
@gixid192 I've just set up a new composer project with PHPMailer.

I created the file 'testmail.php' in the project's root directory. It's contents are a trimmed-down version of the example contained within PHPMailer's github README file, as follows:

```
<?php
// Import PHPMailer classes into the global namespace
// These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

//Load Composer's autoloader
require 'vendor/autoload.php';

$mail = new PHPMailer(true);                              // Passing `true` enables exceptions
try {
    //Server settings
    $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp1.example.com;smtp2.example.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'user@example.com';                 // SMTP username
    $mail->Password = 'secret';                           // SMTP password
    $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 587;                                    // TCP port to connect to

    //Recipients
    $mail->setFrom('from@example.com', 'Mailer');
    $mail->addAddress('joe@example.net', 'Joe User');     // Add a recipient
    $mail->addReplyTo('info@example.com', 'Information');

    //Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'Here is the subject';
    $mail->Body    = 'This is the HTML message body <b>in bold!</b>';
    $mail->AltBody = 'This is the body in plain text for non-HTML mail clients';

    $mail->send();
    echo 'Message has been sent';
} catch (Exception $e) {
    echo 'Message could not be sent. Mailer Error: ', $mail->ErrorInfo;
}
```

I replaced the host with smtp.zoho.com, replaced the sender and return to address with the one configured in magento and replaced the recipient address with my own personal e-mail address. The message is sent successfully.

I recieve no error logs and the e-mail appears in my inbox as expected.

Is this evidence enough that the problem lies within this module/magento?

Thanks.

**Comment by JoshuaFlood** [comment]
@gixid192 Tests were successful so I've just opened issue #101 cos this one seems stale.
