### ISSUE TITLE
Keep getting warning message to activate

### ISSUE THREAD

**Issue by clementblanco** [mageplaza/magento-2-smtp#50]
Once installed this module via composer I keep seeing a warning message about activation.
```
One or more Mageplaza extensions are not validated. Click here to validate them.
```
When **[here](#)** is clicked, nothing to do on the plugin setup page.

**Comment by imsamthomas** [comment]
HI @clementblanco,

Thanks for using our extension.

## Step 1. Make sure you installed latest Mageplaza_Core

**Install**
```
composer require mageplaza/module-core
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
```

**Update**
```
composer update mageplaza/module-core
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy
```

## 2.  Activate

You can go to `Mageplaza > SMTP > Configuration > Module Information`
Next fill required information and click **Activate**

**Comment by clementblanco** [comment]
It's a free extension, this kind of menu "Module Information" is not available.

**Comment by gixid192** [comment]
Hi @clementblanco,

You can open Configuration Settings, you will see it as in this picture
![image](https://content.screencast.com/users/Lovemagic/folders/Jing/media/b37f64cd-727d-4de9-8eb6-1fc79ad4a00c/2018-03-02_1824.png)

**Comment by imsamthomas** [comment]
Hi @clementblanco,

SMTP has **Module Information** menu

**Comment by clementblanco** [comment]
Guys,

thanks for looking at this but this is what I see...
![image 2018-03-02 at 3 32 35 pm](https://user-images.githubusercontent.com/668419/36906899-10b921ba-1e2f-11e8-974b-bd40a52bcc70.png)

**Comment by clementblanco** [comment]
Based on my `composer.lock` file I'm also using `1.1.2`:

```json
        ...
        {
            "name": "mageplaza/module-smtp",
            "version": "1.1.2",
            "source": {
                "type": "git",
                "url": "https://github.com/mageplaza/magento-2-smtp.git",
                "reference": "c424bef0d2ad2a8c84db1b7bd91bbd575fdba0d2"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/mageplaza/magento-2-smtp/zipball/c424bef0d2ad2a8c84db1b7bd91bbd575fdba0d2",
                "reference": "c424bef0d2ad2a8c84db1b7bd91bbd575fdba0d2",
                "shasum": ""
            },
            "require": {
                "mageplaza/module-core": "^1.3.8"
            },
            "type": "magento2-module",
            "autoload": {
                "psr-4": {
                    "Mageplaza\\Smtp\\": ""
                },
                "files": [
                    "registration.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "Mageplaza License"
            ],
            "authors": [
                {
                    "name": "Mageplaza",
                    "email": "hi@mageplaza.com",
                    "homepage": "https://www.mageplaza.com",
                    "role": "Leader"
                }
            ],
            "description": "SMTP Extension for Magento 2 helps the owner of store simply install SMTP (Simple Mail Transfer Protocol) server which transmits the messages into codes or numbers",
            "keywords": [
                "email settings",
                "gmail smtp",
                "magento 2",
                "magento 2 smtp",
                "magento smtp",
                "mageplaza",
                "smtp"
            ],
            "time": "2018-01-05T07:27:08+00:00"
        },
        ...
```

**Comment by imsamthomas** [comment]
It seems your store using [an old version of SMTP](https://github.com/mageplaza/magento-2-smtp/releases) + [Mageplaza_Core](https://github.com/mageplaza/module-core).
You should upgrade it by following [this guide](#issuecomment-369806181)

**Comment by clementblanco** [comment]
I've tried running:
- `composer remove mageplaza/module-smtp`
which gives:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 2 removals
  - Removing mageplaza/module-smtp (1.1.2)
Removing Mageplaza/Smtp
  - Removing mageplaza/module-core (1.3.9)
Removing Mageplaza/Core
Writing lock file
Generating autoload files
```
then:
- `composer require mageplaza/module-smtp`
- `bin/magento setup:upgrade`
which gives:
```
Using version ^1.1 for mageplaza/module-smtp
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 install, 0 updates, 0 removals
  - Installing mageplaza/module-core (1.3.9): Downloading (100%)
  - Installing mageplaza/module-smtp (1.1.2): Downloading (100%)
Writing lock file
Generating autoload files
```

Unfortunately, still the same issue, can't see that menu entry you're talking about.

**Comment by gixid192** [comment]
Please try running the upgrade again (and deploy if needed)

**Comment by imsamthomas** [comment]
Hi,

Try to contact support@mageplaza.com
We will access to your site for furture info.

**Comment by flavioamello** [comment]
I have the same issue, I installed it using composer, today.

**Comment by clementblanco** [comment]
It’s on my local host.
Website is not online.
No need to deploy static assets.

Clément Blanco

On 3 Mar 2018, at 15:10, flavioamello <notifications@github.com> wrote:

I have the same issue, I installed it using composer, today.

**Comment by clementblanco** [comment]
Any update ?

**Comment by imsamthomas** [comment]
We have fixed this issue on [v1.1.2](https://github.com/mageplaza/magento-2-smtp/releases/tag/v1.1.2)

**Comment by kirashet** [comment]
Just pulled the newest version 1.2.10 from GitHub and I'm getting the activation message.

When I click 'Activate Now', nothing happens.

Am I the only one?

**Comment by RimpalBhensdadia** [comment]
You should upgrade Mageplaza core module also: https://github.com/mageplaza/module-core

**Comment by Gypsy7** [comment]
> You should upgrade Mageplaza core module also: https://github.com/mageplaza/module-core

I have upgraded core and still getting the same error. any advice?

[http://prntscr.com/nu83dv](url)

**Comment by deepaksnair123** [comment]
@Gypsy7 , I was also having issue that after clicking on ACTIVATE button, it was not working.
i have updated complete module core and smtp from github and run all commads and it resolved my issue.
Module Core : https://github.com/mageplaza/module-core/
Module SMTP : https://github.com/mageplaza/magento-2-smtp/

**Comment by deepaksnair123** [comment]
@Gypsy7 , I was also having issue that after clicking on ACTIVATE button, it was not working.
i have updated complete module core and smtp from github and run all commads and it resolved my issue.
Module Core : https://github.com/mageplaza/module-core/
Module SMTP : https://github.com/mageplaza/magento-2-smtp/

**Comment by imeshl** [comment]
I am getting the same error after updating Magento to 2.2.11. Mageplaza modules are all up to date. I'm using Recaptcha & SEO modules. Any solution for this?

**Comment by Mart-ASE** [comment]
I am also experiencing this error and I don't know how to solve it
