### ISSUE TITLE
After save test fails with 5.7.8 Authentication credentials invalid

### ISSUE THREAD

**Issue by SnowCommerceBrand** [mageplaza/magento-2-smtp#85]
Hello,

I am using newest version 1.2.0 composer install and latest core.

Here is the scenario: 
Enter Credentials send test email button Success and I get email.

Hit save button in magento.
Password looks to shorter and changed when page refreshes
doing a test I get 5.7.8 Authentication credentials invalid

I am running magento 2.2.4 

In core config I see my username correct and encrypted password is there some trouble with test not using the encoded password and using the ***** that it gets replaced with in admin view?

![image](https://user-images.githubusercontent.com/37154233/41170805-f45d0c0e-6b1b-11e8-9124-70e51754b761.png)

**Comment by gixid192** [comment]
- The * is just a marker, it doesn't change your password.

Are you using multistore in your website?

**Comment by gixid192** [comment]
@SnowCommerceBrand the issue has been fixed in version 1.2.1, kindly help us check again.
Thank you.

**Comment by SnowCommerceBrand** [comment]
@gixid192 Thanks for the quick response.

Yes I am using a multi store website each store has its own SMTP email server username and password. I think there might be a issue here also with the getSmtpConfig in Data.php. We need to get SMTP from the Website Level / Store Level not just default for username and password ext.

It looks like getTransport($storeId) from Rse/Mail.php is responsible for calling out to getSmtpConfig where we are getting config from default level user / password and not the store. I can create a test case and pull request if it works. 

https://github.com/mageplaza/magento-2-smtp/blob/master/Helper/Data.php
https://github.com/mageplaza/magento-2-smtp/blob/master/Mail/Rse/Mail.php

**Comment by gixid192** [comment]
@SnowCommerceBrand How it went with the new version? Could you let me know the result?

**Comment by SnowCommerceBrand** [comment]
I tested the test email send button with new version on the website configuration it worked. I still have an issue when Cron loads emails that send from store level config I will look for exception message. But I think issue could be with get password or transport function.

**Comment by SnowCommerceBrand** [comment]
@pkd87 can you also confirm any issue around email config not working at website / store level for credentials. Always pulls default config.

**Comment by gixid192** [comment]
Hey guys, is everything all right?

**Comment by gixid192** [comment]
Close due to no response within 7 days.
